class Cols(object):
    mes = "MES"
    n = "N"
    mes_grafica = "MES GRAFICA"
    fecha_visita = "FECHA VISITA"
    hitos = "HITOS"
    tipo_hito = "TIPO HITO"
    parcial_planificacion_inicial = "Parcial Planificacion Inicial"
    acumulado_planificacion_inicial = "Acumulado Planificacion Inicial"
    planificación_inicial = "Planificación Inicial"
    actualizacion_1_parcial = "Actualizacion 1 Parcial"
    actualizacion_1_acumulado = "Actualizacion 1 Acumulado"
    actualizacion_2_parcial = "Actualizacion 2 Parcial"
    actualizacion_2_acumulado = "Actualizacion 2 Acumulado"
    actualizacion_3_parcial = "Actualizacion 3 Parcial"
    actualizacion_3_acumulado = "Actualizacion 3 Acumulado"
    parcial_planificacion_actualizada = "Parcial Planificacion Actualizada"
    acumulado_planificacion_actualizada = "Acumulado Planificacion Actualizada"
    planificacion_actualizada = "Planificacion Actualizada"
    parcial_certificado = "Parcial Certificado"
    acumulado_certificado = "Acumulado Certificado"
    avance_obra = "Avance Obra"
    desviacion_origen_eur = "Desviación Origen (€)"
    desviacion_origen_percent = "Desviación Origen (%)"
    grafica_planificacion_stc_inicial = "GRAFICA Planificacion STC Inicial"
    grafica_planificacion_stc_actualizada = "GRAFICA Planificacion STC Actualizada"
    grafica_planificacion_contratista_inicial = "GRAFICA Planificacion Contratista Inicial"
    grafica_planificacion_contratista_actualizada = "GRAFICA Planificacion Contratista Actualizada"
    grafica_avance_comercialización_ = "GRAFICA Avance comercialización (%)"
    grafica_mes_vigente_anterior = "GRAFICA Mes Vigente_Anterior"
    grafica_mes_posterior = "GRAFICA Mes Posterior"
    gráfica_ficha = "GRÁFICA FICHA"
    gauss_parcial_stc = "GAUSS Parcial STC"
    gauss_acumulado_stc = "GAUSS Acumulado STC"
    gauss_previsión_stc = "GAUSS Previsión STC"
    gauss_parcial_stc = "GAUSS % Parcial STC"
    gauss_origen_distr_normal = "GAUSS % Origen Distr. Normal"


class PLANIFICACION_DATA:
    igual_prevision_inicial = "Igual a Previsión Inicial"
    STC = "STC"
    Contratista = "Contratista"
